version: '2'

services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"

    web:
        build: .
        container_name: web_book
        working_dir: /usr/src/app
        ports:
            - "3000:3000"

    
